// <auto-generated />
using CrudTest.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudTest.Migrations
{
    [DbContext(typeof(CrudTestDbContext))]
    [Migration("20191124052558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("CrudTest.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("RealName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Email = "john@beatles.com", Name = "jlennon", RealName = "John Lennon" },
                        new { Id = 2, Email = "paul@beatles.com", Name = "paulm", RealName = "Paul McCartney" },
                        new { Id = 3, Email = "george@beatles.com", Name = "gharrison", RealName = "George Harrison" },
                        new { Id = 4, Email = "ringo@beatles.com", Name = "rstarr", RealName = "Richard Starkey" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
